/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  About: () => import('#controllers/about_controller'),
  BomShares: () => import('#controllers/bom_shares_controller'),
  Decisions: () => import('#controllers/decisions_controller'),
  Dependencies: () => import('#controllers/dependencies_controller'),
  Duplicates: () => import('#controllers/duplicates_controller'),
  Home: () => import('#controllers/home_controller'),
  Isolation: () => import('#controllers/isolation_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oidc: () => import('#controllers/oidc_controller'),
  Releases: () => import('#controllers/releases_controller'),
  Repositories: () => import('#controllers/repositories_controller'),
  Session: () => import('#controllers/session_controller'),
  Spend: () => import('#controllers/spend_controller'),
  Turns: () => import('#controllers/turns_controller'),
  Webhooks: () => import('#controllers/webhooks_controller'),
  Workspaces: () => import('#controllers/workspaces_controller'),
}
