/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditAnchorSchema extends BaseModel {
  static $columns = ['anchoredAt', 'headHash', 'id', 'location', 'seq', 'workspaceId'] as const
  $columns = AuditAnchorSchema.$columns
  @column.dateTime()
  declare anchoredAt: DateTime
  @column()
  declare headHash: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare location: string
  @column()
  declare seq: bigint | number
  @column()
  declare workspaceId: string
}

export class AuditBatchSchema extends BaseModel {
  static $columns = ['fromSeq', 'headHash', 'id', 'keyId', 'signature', 'toSeq', 'workspaceId', 'writtenAt'] as const
  $columns = AuditBatchSchema.$columns
  @column()
  declare fromSeq: bigint | number
  @column()
  declare headHash: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyId: string
  @column()
  declare signature: string
  @column()
  declare toSeq: bigint | number
  @column()
  declare workspaceId: string
  @column.dateTime()
  declare writtenAt: DateTime
}

export class AuditEventSchema extends BaseModel {
  static $columns = ['batchId', 'event', 'hash', 'occurredAt', 'payload', 'prevHash', 'seq', 'workspaceId'] as const
  $columns = AuditEventSchema.$columns
  @column()
  declare batchId: string
  @column()
  declare event: string
  @column()
  declare hash: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare payload: any
  @column()
  declare prevHash: string
  @column()
  declare seq: bigint | number
  @column({ isPrimary: true })
  declare workspaceId: string
}

export class AuditOutboxSchema extends BaseModel {
  static $columns = ['createdAt', 'event', 'id', 'payload', 'workspaceId'] as const
  $columns = AuditOutboxSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare payload: any
  @column()
  declare workspaceId: string
}

export class AuditVerificationSchema extends BaseModel {
  static $columns = ['id', 'keyId', 'ok', 'verifiedAt'] as const
  $columns = AuditVerificationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyId: string
  @column()
  declare ok: boolean
  @column.dateTime()
  declare verifiedAt: DateTime
}

export class BlobSchema extends BaseModel {
  static $columns = ['blobSha', 'content', 'contentSha256', 'createdAt', 'redacted', 'size', 'skipReason', 'workspaceId'] as const
  $columns = BlobSchema.$columns
  @column()
  declare blobSha: string
  @column()
  declare content: string | null
  @column()
  declare contentSha256: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare redacted: boolean
  @column()
  declare size: number
  @column()
  declare skipReason: string | null
  @column({ isPrimary: true })
  declare workspaceId: string
}

export class BomShareLinkSchema extends BaseModel {
  static $columns = ['commitId', 'createdAt', 'createdBy', 'expiresAt', 'format', 'handle', 'id', 'repositoryId', 'revokedAt', 'revokedBy', 'turnId', 'workspaceId'] as const
  $columns = BomShareLinkSchema.$columns
  @column()
  declare commitId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare format: string
  @column()
  declare handle: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare repositoryId: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedBy: number | null
  @column()
  declare turnId: string
  @column()
  declare workspaceId: string
}

export class BomShareRouteSchema extends BaseModel {
  static $columns = ['actsAsUserId', 'linkId', 'tokenHash', 'workspaceId'] as const
  $columns = BomShareRouteSchema.$columns
  @column()
  declare actsAsUserId: number
  @column()
  declare linkId: string
  @column({ isPrimary: true })
  declare tokenHash: string
  @column()
  declare workspaceId: string
}

export class ChunkSchema extends BaseModel {
  static $columns = ['blobSha', 'chunkerVersion', 'commitId', 'embedding', 'embeddingKey', 'endLine', 'flaggedWindow', 'id', 'injectionSuspected', 'path', 'scanVersion', 'searchText', 'searchTsv', 'startLine', 'symbolId', 'text', 'workspaceId'] as const
  $columns = ChunkSchema.$columns
  @column()
  declare blobSha: string
  @column()
  declare chunkerVersion: string
  @column()
  declare commitId: string
  @column()
  declare embedding: any | null
  @column()
  declare embeddingKey: string | null
  @column()
  declare endLine: number
  @column()
  declare flaggedWindow: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare injectionSuspected: boolean
  @column()
  declare path: string
  @column()
  declare scanVersion: string | null
  @column()
  declare searchText: string
  @column()
  declare searchTsv: string | null
  @column()
  declare startLine: number
  @column()
  declare symbolId: string | null
  @column()
  declare text: string
  @column()
  declare workspaceId: string
}

export class CitationBlockSchema extends BaseModel {
  static $columns = ['endLine', 'id', 'ordinal', 'startLine', 'symbolId', 'workspaceId'] as const
  $columns = CitationBlockSchema.$columns
  @column()
  declare endLine: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ordinal: number
  @column()
  declare startLine: number
  @column()
  declare symbolId: string
  @column()
  declare workspaceId: string
}

export class CloneClassSchema extends BaseModel {
  static $columns = ['classification', 'commitId', 'id', 'method', 'similarity', 'size', 'type', 'workspaceId'] as const
  $columns = CloneClassSchema.$columns
  @column()
  declare classification: string
  @column()
  declare commitId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare method: string
  @column()
  declare similarity: number
  @column()
  declare size: number
  @column()
  declare type: number
  @column()
  declare workspaceId: string
}

export class CloneMemberSchema extends BaseModel {
  static $columns = ['classId', 'divergence', 'endLine', 'id', 'path', 'qualifiedName', 'startLine', 'tokens', 'workspaceId'] as const
  $columns = CloneMemberSchema.$columns
  @column()
  declare classId: string
  @column()
  declare divergence: any
  @column()
  declare endLine: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare path: string
  @column()
  declare qualifiedName: string
  @column()
  declare startLine: number
  @column()
  declare tokens: number
  @column()
  declare workspaceId: string
}

export class CloneSignatureSchema extends BaseModel {
  static $columns = ['band', 'commitId', 'endLine', 'id', 'path', 'qualifiedName', 'startLine', 'workspaceId'] as const
  $columns = CloneSignatureSchema.$columns
  @column()
  declare band: string
  @column()
  declare commitId: string
  @column()
  declare endLine: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare path: string
  @column()
  declare qualifiedName: string
  @column()
  declare startLine: number
  @column()
  declare workspaceId: string
}

export class CommitHistorySchema extends BaseModel {
  static $columns = ['bulkSkipped', 'commitId', 'commitsRead', 'reasonCode', 'recordedAt', 'status', 'workspaceId'] as const
  $columns = CommitHistorySchema.$columns
  @column()
  declare bulkSkipped: number
  @column({ isPrimary: true })
  declare commitId: string
  @column()
  declare commitsRead: number
  @column()
  declare reasonCode: string | null
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare status: string
  @column()
  declare workspaceId: string
}

export class CommitSchema extends BaseModel {
  static $columns = ['committedAt', 'createdAt', 'id', 'indexedAt', 'objectFormat', 'parentShas', 'repositoryId', 'sha', 'status', 'workspaceId'] as const
  $columns = CommitSchema.$columns
  @column.dateTime()
  declare committedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare indexedAt: DateTime | null
  @column()
  declare objectFormat: string
  @column()
  declare parentShas: any
  @column()
  declare repositoryId: string
  @column()
  declare sha: string
  @column()
  declare status: string
  @column()
  declare workspaceId: string
}

export class DependencySchema extends BaseModel {
  static $columns = ['commitId', 'ecosystem', 'id', 'importers', 'integrity', 'kind', 'line', 'manifest', 'name', 'resolved', 'tier1Status', 'version', 'workspaceId'] as const
  $columns = DependencySchema.$columns
  @column()
  declare commitId: string
  @column()
  declare ecosystem: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importers: any
  @column()
  declare integrity: string | null
  @column()
  declare kind: string
  @column()
  declare line: number | null
  @column()
  declare manifest: string
  @column()
  declare name: string
  @column()
  declare resolved: string | null
  @column()
  declare tier1Status: string
  @column()
  declare version: string
  @column()
  declare workspaceId: string
}

export class DependencySymbolSchema extends BaseModel {
  static $columns = ['declaration', 'fetchedAt', 'id', 'kind', 'line', 'name', 'package', 'path', 'registry', 'version'] as const
  $columns = DependencySymbolSchema.$columns
  @column()
  declare declaration: string
  @column.dateTime()
  declare fetchedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare line: number
  @column()
  declare name: string
  @column()
  declare package: string
  @column()
  declare path: string
  @column()
  declare registry: string
  @column()
  declare version: string
}

export class DerivationCacheSchema extends BaseModel {
  static $columns = ['createdAt', 'key', 'kind', 'value', 'workspaceId'] as const
  $columns = DerivationCacheSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare key: string
  @column()
  declare kind: string
  @column()
  declare value: any
  @column({ isPrimary: true })
  declare workspaceId: string
}

export class EndpointSchema extends BaseModel {
  static $columns = ['commitId', 'file', 'framework', 'handler', 'id', 'line', 'method', 'path', 'workspaceId'] as const
  $columns = EndpointSchema.$columns
  @column()
  declare commitId: string
  @column()
  declare file: string
  @column()
  declare framework: string
  @column()
  declare handler: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare line: number
  @column()
  declare method: string
  @column()
  declare path: string
  @column()
  declare workspaceId: string
}

export class FileCochangeSchema extends BaseModel {
  static $columns = ['changesA', 'changesB', 'commitId', 'pathA', 'pathB', 'together', 'workspaceId'] as const
  $columns = FileCochangeSchema.$columns
  @column()
  declare changesA: number
  @column()
  declare changesB: number
  @column({ isPrimary: true })
  declare commitId: string
  @column()
  declare pathA: string
  @column()
  declare pathB: string
  @column()
  declare together: number
  @column()
  declare workspaceId: string
}

export class FileSchema extends BaseModel {
  static $columns = ['blobSha', 'change', 'commitId', 'ignoredBy', 'mode', 'path', 'workspaceId'] as const
  $columns = FileSchema.$columns
  @column()
  declare blobSha: string
  @column()
  declare change: string
  @column({ isPrimary: true })
  declare commitId: string
  @column()
  declare ignoredBy: string | null
  @column()
  declare mode: string
  @column()
  declare path: string
  @column()
  declare workspaceId: string
}

export class HoneytokenSchema extends BaseModel {
  static $columns = ['createdAt', 'embedding', 'id', 'searchText', 'searchTsv', 'text', 'token', 'workspaceId'] as const
  $columns = HoneytokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare embedding: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare searchText: string
  @column()
  declare searchTsv: string | null
  @column()
  declare text: string
  @column()
  declare token: string
  @column()
  declare workspaceId: string
}

export class IngestStepSchema extends BaseModel {
  static $columns = ['actorUserId', 'commitSha', 'finishedAt', 'progress', 'repositoryId', 'result', 'startedAt', 'status', 'step', 'workspaceId'] as const
  $columns = IngestStepSchema.$columns
  @column()
  declare actorUserId: number | null
  @column()
  declare commitSha: string
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare progress: any | null
  @column({ isPrimary: true })
  declare repositoryId: string
  @column()
  declare result: any
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare step: string
  @column()
  declare workspaceId: string
}

export class LlmUsageSchema extends BaseModel {
  static $columns = ['cacheCreationTokens', 'cacheReadTokens', 'endedAt', 'id', 'inputTokens', 'jti', 'model', 'outputTokens', 'purpose', 'requestId', 'startedAt', 'status', 'turnHandle', 'userId', 'workspaceId'] as const
  $columns = LlmUsageSchema.$columns
  @column()
  declare cacheCreationTokens: number | null
  @column()
  declare cacheReadTokens: number | null
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inputTokens: number | null
  @column()
  declare jti: string | null
  @column()
  declare model: string
  @column()
  declare outputTokens: number | null
  @column()
  declare purpose: string
  @column()
  declare requestId: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare turnHandle: string | null
  @column()
  declare userId: number
  @column()
  declare workspaceId: string
}

export class ManifestSchema extends BaseModel {
  static $columns = ['commitId', 'dependencies', 'ecosystem', 'id', 'path', 'status', 'workspaceId'] as const
  $columns = ManifestSchema.$columns
  @column()
  declare commitId: string
  @column()
  declare dependencies: number
  @column()
  declare ecosystem: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare path: string
  @column()
  declare status: string
  @column()
  declare workspaceId: string
}

export class RedactionSchema extends BaseModel {
  static $columns = ['blobSha', 'fingerprint', 'line', 'rule', 'workspaceId'] as const
  $columns = RedactionSchema.$columns
  @column()
  declare blobSha: string
  @column()
  declare fingerprint: string
  @column()
  declare line: number
  @column()
  declare rule: string
  @column({ isPrimary: true })
  declare workspaceId: string
}

export class RefSchema extends BaseModel {
  static $columns = ['commitSha', 'name', 'repositoryId', 'updatedAt', 'workspaceId'] as const
  $columns = RefSchema.$columns
  @column()
  declare commitSha: string
  @column()
  declare name: string
  @column({ isPrimary: true })
  declare repositoryId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare workspaceId: string
}

export class RepoFactSchema extends BaseModel {
  static $columns = ['commitId', 'facts', 'profile', 'workspaceId'] as const
  $columns = RepoFactSchema.$columns
  @column({ isPrimary: true })
  declare commitId: string
  @column()
  declare facts: any
  @column()
  declare profile: string
  @column()
  declare workspaceId: string
}

export class RepositorySchema extends BaseModel {
  static $columns = ['activeCommitId', 'createdAt', 'defaultRef', 'handle', 'id', 'ignorePaths', 'name', 'status', 'statusDetail', 'updatedAt', 'url', 'visibility', 'workspaceId'] as const
  $columns = RepositorySchema.$columns
  @column()
  declare activeCommitId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultRef: string
  @column()
  declare handle: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ignorePaths: any | null
  @column()
  declare name: string
  @column()
  declare status: string
  @column()
  declare statusDetail: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare visibility: string
  @column()
  declare workspaceId: string
}

export class RepositoryMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'repositoryId', 'userId', 'workspaceId'] as const
  $columns = RepositoryMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare repositoryId: string
  @column()
  declare userId: number
  @column()
  declare workspaceId: string
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class SymbolReferenceSchema extends BaseModel {
  static $columns = ['commitId', 'fromSymbolId', 'id', 'kind', 'line', 'path', 'resolution', 'targetName', 'toExternal', 'toSymbolId', 'workspaceId'] as const
  $columns = SymbolReferenceSchema.$columns
  @column()
  declare commitId: string
  @column()
  declare fromSymbolId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare line: number
  @column()
  declare path: string
  @column()
  declare resolution: string
  @column()
  declare targetName: string | null
  @column()
  declare toExternal: string | null
  @column()
  declare toSymbolId: string | null
  @column()
  declare workspaceId: string
}

export class SymbolSchema extends BaseModel {
  static $columns = ['blobSha', 'commitId', 'endLine', 'id', 'kind', 'language', 'name', 'parent', 'path', 'qualifiedName', 'startLine', 'workspaceId'] as const
  $columns = SymbolSchema.$columns
  @column()
  declare blobSha: string
  @column()
  declare commitId: string
  @column()
  declare endLine: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare language: string
  @column()
  declare name: string
  @column()
  declare parent: string | null
  @column()
  declare path: string
  @column()
  declare qualifiedName: string
  @column()
  declare startLine: number
  @column()
  declare workspaceId: string
}

export class ThreadSchema extends BaseModel {
  static $columns = ['createdAt', 'handle', 'id', 'repositoryId', 'userId', 'workspaceId'] as const
  $columns = ThreadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare handle: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare repositoryId: string
  @column()
  declare userId: number
  @column()
  declare workspaceId: string
}

export class TurnCitationSchema extends BaseModel {
  static $columns = ['blobSha', 'commitSha', 'endLine', 'handle', 'id', 'path', 'spanSha256', 'startLine', 'turnId', 'workspaceId'] as const
  $columns = TurnCitationSchema.$columns
  @column()
  declare blobSha: string
  @column()
  declare commitSha: string
  @column()
  declare endLine: number
  @column()
  declare handle: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare path: string
  @column()
  declare spanSha256: string
  @column()
  declare startLine: number
  @column()
  declare turnId: string
  @column()
  declare workspaceId: string
}

export class TurnSchema extends BaseModel {
  static $columns = ['answerSalt', 'answerText', 'citationHandles', 'commitId', 'configHash', 'createdAt', 'erasedAt', 'events', 'id', 'question', 'questionSalt', 'released', 'runHandle', 'runState', 'scopeLabel', 'strictRegenerated', 'threadId', 'traceId', 'withheldSalt', 'withheldText', 'workspaceId'] as const
  $columns = TurnSchema.$columns
  @column()
  declare answerSalt: string | null
  @column()
  declare answerText: string
  @column()
  declare citationHandles: any
  @column()
  declare commitId: string
  @column()
  declare configHash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare erasedAt: DateTime | null
  @column()
  declare events: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare question: string
  @column()
  declare questionSalt: string | null
  @column()
  declare released: boolean
  @column()
  declare runHandle: string
  @column()
  declare runState: string
  @column()
  declare scopeLabel: string | null
  @column()
  declare strictRegenerated: boolean
  @column()
  declare threadId: string
  @column()
  declare traceId: string | null
  @column()
  declare withheldSalt: string | null
  @column()
  declare withheldText: string
  @column()
  declare workspaceId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'oid', 'password', 'tid', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare oid: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare tid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WebhookDeliverySchema extends BaseModel {
  static $columns = ['deliveryId', 'outcome', 'receivedAt', 'repositoryId', 'workspaceId'] as const
  $columns = WebhookDeliverySchema.$columns
  @column()
  declare deliveryId: string
  @column()
  declare outcome: string
  @column.dateTime()
  declare receivedAt: DateTime
  @column({ isPrimary: true })
  declare repositoryId: string
  @column()
  declare workspaceId: string
}

export class WebhookEndpointSchema extends BaseModel {
  static $columns = ['actsAsUserId', 'createdAt', 'handle', 'repositoryId', 'secret', 'workspaceId'] as const
  $columns = WebhookEndpointSchema.$columns
  @column()
  declare actsAsUserId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare handle: string
  @column()
  declare repositoryId: string
  @column()
  declare secret: string
  @column()
  declare workspaceId: string
}

export class WorkerJobHeartbeatSchema extends BaseModel {
  static $columns = ['beatAt', 'jobId', 'workerId'] as const
  $columns = WorkerJobHeartbeatSchema.$columns
  @column.dateTime()
  declare beatAt: DateTime
  @column({ isPrimary: true })
  declare jobId: string
  @column()
  declare workerId: string
}

export class WorkspaceMembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'userId', 'workspaceId'] as const
  $columns = WorkspaceMembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: string
  @column()
  declare userId: number
  @column()
  declare workspaceId: string
}

export class WorkspaceSchema extends BaseModel {
  static $columns = ['createdAt', 'handle', 'id', 'name', 'updatedAt'] as const
  $columns = WorkspaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare handle: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
