/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type RepositoryTransformer from '#transformers/repository_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type WorkspaceTransformer from '#transformers/workspace_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Repository = InferData<RepositoryTransformer>
  export namespace Repository {
    export type Variants = InferVariants<RepositoryTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type Workspace = InferData<WorkspaceTransformer>
  export namespace Workspace {
    export type Variants = InferVariants<WorkspaceTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
