import { readFile } from 'node:fs/promises'
import { parse } from 'yaml'
import type { CaseFile } from './runner.js'

/**
 * Traceability (design §12 stage 5c, AC-WP10-04/05): every threat in
 * threats.yaml has a frozen case; every mitigation has an ablation flag or a
 * recorded reason; the matrix lists threat, mitigations, cases and the last
 * structural result.
 */
export interface Threat {
  id: string
  name: string
  owasp: Record<string, string[]>
  entry_points: string[]
  mitigations: Record<string, string[]>
  checks: string[]
}

export async function loadThreats(path = 'evals/redteam/threats.yaml'): Promise<Threat[]> {
  return (parse(await readFile(path, 'utf8')) as { threats: Threat[] }).threats
}

export interface Coverage {
  threatsWithoutCase: string[]
  mitigationsWithoutAblationOrReason: string[]
  unknownMitigationsInCases: string[]
}

export function coverage(
  threats: Threat[],
  cases: CaseFile,
  ablations: Record<string, { ablation?: string; reason?: string }>,
  flags: readonly string[]
): Coverage {
  const covered = new Set(cases.cases.map((c) => c.threat))
  const named = new Set(threats.flatMap((t) => Object.values(t.mitigations).flat()))
  const bad: string[] = []
  for (const m of named) {
    const entry = ablations[m]
    if (!entry || (!entry.reason && !(entry.ablation && flags.includes(entry.ablation))))
      bad.push(m)
  }
  return {
    threatsWithoutCase: threats.map((t) => t.id).filter((id) => !covered.has(id)),
    mitigationsWithoutAblationOrReason: bad,
    unknownMitigationsInCases: Array.from(
      new Set(cases.cases.flatMap((c) => c.mitigations).filter((m) => !named.has(m)))
    ),
  }
}

export interface LastResult {
  reports: Array<{
    id: string
    threat: string
    runner: string
    hardened: { pass: boolean; blockedBy: string } | null
    discriminates: boolean | null
    testTag?: string
  }>
}

export function renderMatrix(threats: Threat[], cases: CaseFile, last: LastResult | null): string {
  const lines = [
    '# Red-team traceability matrix',
    '',
    'Generated by `node ace docs:trace`; source of truth is `evals/redteam/threats.yaml`, `evals/redteam/cases/regression.json` and the last `redteam:run`.',
    '',
    '| threat | name | OWASP | mitigations | cases | last result |',
    '|---|---|---|---|---|---|',
  ]
  for (const t of threats) {
    const mine = cases.cases.filter((c) => c.threat === t.id)
    const result = mine
      .map((c) => {
        const r = last?.reports.find((x) => x.id === c.id)
        if (!r) return `${c.id}: not run`
        return r.hardened
          ? `${c.id}: ${r.hardened.pass ? 'pass' : 'FAIL'} (${r.hardened.blockedBy}${r.discriminates ? ', discriminates' : ''})`
          : `${c.id}: via ${r.testTag}`
      })
      .join('<br>')
    lines.push(
      `| ${t.id} | ${t.name} | ${Object.values(t.owasp).flat().join(', ')} | ${Object.entries(
        t.mitigations
      )
        .map(([l, ms]) => `${l}: ${ms.join(', ')}`)
        .join('<br>')} | ${mine.map((c) => c.id).join('<br>') || '—'} | ${result || '—'} |`
    )
  }
  return lines.join('\n') + '\n'
}
